### ISSUE TITLE
i got the actual aurora v2 source code

### ISSUE THREAD

**Issue by omairma** [AlexDev404/Aurora-v2#1]
i got the aurora v2 source code before you
how do you feel

**Comment by PeQuLeaks** [comment]
W for irma

**Comment by Kian738** [comment]
lol nice to see you here irma

**Comment by Slushia** [comment]
irma i  am big fan of yours can i plaease have hte source code !?!

**Comment by Kian738** [comment]
Lol even Slushia is here wtf

**Comment by Slushia** [comment]
dog with hat pfp says what

**Comment by Kian738** [comment]
Wtf how do you know my discord
